# Generated by Django 5.1.7 on 2025-03-14 14:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название кнопки')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='footer/icons', verbose_name='Иконка')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
                'ordering': ('order',),
            },
        ),
    ]
