# Generated by Django 5.1.7 on 2025-03-31 14:37

from django.db import migrations, models
from common.models import Contacts

def copy_existing_data(apps, schema_editor):
    Contacts = apps.get_model("common", "Contacts")
    for contact in Contacts.objects.all():
        contact.address_ru = contact.address_ru

        contact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
    ]
