# Generated by Django 5.1.7 on 2025-03-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items', verbose_name='Главная картинка товара')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Цена')),
                ('production', models.CharField(max_length=255, verbose_name='Производство')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('is_available', models.BooleanField(default=False, verbose_name='Наличие')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
            ],
        ),
    ]
