# Generated by Django 5.1.7 on 2025-03-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/img_box ', verbose_name='Главная картинка товара'),
        ),
    ]
