# Generated by Django 5.1.7 on 2025-03-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/img_box', verbose_name='Главная картинка товара'),
        ),
    ]
