# Generated by Django 5.1.7 on 2025-03-18 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_user_item_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
