# Generated by Django 5.1.7 on 2025-03-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_delete_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(related_name='Items', to='users.customuser'),
        ),
    ]
