# Generated by Django 5.1.7 on 2025-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_item_description_alter_item_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок товара'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='text',
            field=models.TextField(),
        ),
    ]
